version: "3.0"

services:
  app:
    image: rafailmdzdv/hangugeoreul-backend:latest
    ports:
      - 8001:8000
    expose:
      - 8000
    volumes:
      - ./src/config/.env:/app/src/config/.env
      - static_files:/var/www/django/static
    command: >
      bash -c "
      /app/.venv/bin/python /app/src/manage.py migrate
      && /app/.venv/bin/python /app/src/manage.py collectstatic --no-input --dry-run --clear
      && /app/.venv/bin/python /app/src/manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db

  db:
    image: postgres:15.3
    ports:
      - 5433:5432
    expose:
      - 5432
    env_file:
      - ./src/config/.env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - static_files:/var/www/django/static
    depends_on:
      - app

volumes:
  - static_files:
