version: "3.0"

services:
  app:
    image: rafailmdzdv/hangugeoreul-backend:latest
    ports:
      - 8001:8000
    expose:
      - 8000
    volumes:
      - ./src/config/.env:/app/src/config/.env
      - static_files:/var/www/django/static
      - run_dir:/run
    command: >
      bash -c "
      /app/.venv/bin/python /app/src/manage.py migrate
      && /app/.venv/bin/python /app/src/manage.py collectstatic --no-input --clear
      && /app/.venv/bin/gunicorn --bind unix:///run/hangugeo_backend.sock --workers $(expr $(nproc) + 1) --access-logfile gunicorn.log --chdir /app/src server.wsgi:application
      "
    depends_on:
      - db

  db:
    image: postgres:16.2
    ports:
      - 5433:5432
    expose:
      - 5432
    env_file:
      - ./src/config/.env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - static_files:/var/www/django/static
      - run_dir:/run
    depends_on:
      - app

volumes:
  static_files:
  run_dir:
