version: "3.0"

services:
  app:
    image: rafailmdzdv/hangugeoreul-backend:latest
    ports:
      - 8001:8000
    volumes:
      - ./src/config/.env:/app/src/config/.env
    command: >
      bash -c "
      /app/.venv/bin/python /app/src/manage.py migrate
      && /app/.venv/bin/python /app/src/manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db

  db:
    image: postgres:15.5
    ports:
      - 5433:5432
    expose:
      - 5432
    env_file:
      - ./src/config/.env
