# Generated by Django 4.2.7 on 2023-11-02 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.IntegerField(db_index=True, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Study day',
                'verbose_name_plural': 'Study days',
                'db_table': 'study_days',
            },
        ),
    ]
