# Generated by Django 4.2.7 on 2023-11-03 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Id')),
                ('meaning', models.CharField(max_length=40, verbose_name='Meaning')),
                ('translation', models.CharField(max_length=70, verbose_name='Translation')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_days', to='days.studyday', verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'db_table': 'words',
            },
        ),
    ]
