name: Hangugeoreul Gongbuhaeyo CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: 123
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Write envs
        run: echo '${{ secrets.PROJECT_ENVS }}' > src/config/.env

      - name: Migrate
        run: poetry run python src/manage.py migrate

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint with flake8
        run: poetry run flake8

      - name: Lint with pyright
        run: poetry run pyright

      - name: Lint migrations
        run: poetry run python src/manage.py lintmigrations

      - name: Test with pytest
        run: poetry run pytest
